# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_dyad <- function(i, j, c, N, directed) {
    .Call(`_remstats_find_dyad`, i, j, c, N, directed)
}

standardize <- function(stat) {
    .Call(`_remstats_standardize`, stat)
}

compute_adjmat <- function(edgelist, N, D, directed, memory, memory_value, start, stop) {
    .Call(`_remstats_compute_adjmat`, edgelist, N, D, directed, memory, memory_value, start, stop)
}

actorStat_tie <- function(type, covariates, edgelist, actors, types, D, start, stop) {
    .Call(`_remstats_actorStat_tie`, type, covariates, edgelist, actors, types, D, start, stop)
}

dyadStat_tie <- function(type, covariates, edgelist, riskset, start, stop) {
    .Call(`_remstats_dyadStat_tie`, type, covariates, edgelist, riskset, start, stop)
}

inertia_tie <- function(edgelist, adjmat, riskset, N, directed, types, start, stop, consider_type) {
    .Call(`_remstats_inertia_tie`, edgelist, adjmat, riskset, N, directed, types, start, stop, consider_type)
}

reciprocity_tie <- function(edgelist, adjmat, riskset, N, types, start, stop, consider_type) {
    .Call(`_remstats_reciprocity_tie`, edgelist, adjmat, riskset, N, types, start, stop, consider_type)
}

degree_tie <- function(type, edgelist, adjmat, actors, types, start, stop, consider_type) {
    .Call(`_remstats_degree_tie`, type, edgelist, adjmat, actors, types, start, stop, consider_type)
}

degree_undirected_tie <- function(type, edgelist, adjmat, actors, types, start, stop, consider_type) {
    .Call(`_remstats_degree_undirected_tie`, type, edgelist, adjmat, actors, types, start, stop, consider_type)
}

triad_tie <- function(type, edgelist, actors, types, adjmat, riskset, start, stop, consider_type) {
    .Call(`_remstats_triad_tie`, type, edgelist, actors, types, adjmat, riskset, start, stop, consider_type)
}

pshift_tie <- function(type, edgelist, riskset, N, C, start, stop, consider_type) {
    .Call(`_remstats_pshift_tie`, type, edgelist, riskset, N, C, start, stop, consider_type)
}

rankR <- function(x, N) {
    .Call(`_remstats_rankR`, x, N)
}

rrank_tie <- function(type, edgelist, riskset, N, C, start, stop, consider_type) {
    .Call(`_remstats_rrank_tie`, type, edgelist, riskset, N, C, start, stop, consider_type)
}

recency_tie <- function(type, edgelist, riskset, N, C, start, stop, consider_type, directed) {
    .Call(`_remstats_recency_tie`, type, edgelist, riskset, N, C, start, stop, consider_type, directed)
}

tie_tie <- function(covariates, edgelist, riskset, start, stop) {
    .Call(`_remstats_tie_tie`, covariates, edgelist, riskset, start, stop)
}

event_tie <- function(covariates, edgelist, riskset, start, stop) {
    .Call(`_remstats_event_tie`, covariates, edgelist, riskset, start, stop)
}

FEtype_tie <- function(covariates, edgelist, riskset, start, stop) {
    .Call(`_remstats_FEtype_tie`, covariates, edgelist, riskset, start, stop)
}

current_common_partners <- function(edgelist, riskset, actors, duration, start, stop) {
    .Call(`_remstats_current_common_partners`, edgelist, riskset, actors, duration, start, stop)
}

compute_stats_tie <- function(effects, edgelist, adjmat, actors, types, riskset, scaling, covariates, interactions, start, stop, directed, verbose) {
    .Call(`_remstats_compute_stats_tie`, effects, edgelist, adjmat, actors, types, riskset, scaling, covariates, interactions, start, stop, directed, verbose)
}

actorStat_rc <- function(covariates, edgelist, riskset, actors, start, stop, scaling) {
    .Call(`_remstats_actorStat_rc`, covariates, edgelist, riskset, actors, start, stop, scaling)
}

degree_rc <- function(type, riskset, actors, adjmat) {
    .Call(`_remstats_degree_rc`, type, riskset, actors, adjmat)
}

recency_rc <- function(type, edgelist, riskset, N, start, stop) {
    .Call(`_remstats_recency_rc`, type, edgelist, riskset, N, start, stop)
}

dyadStat_choice <- function(type, covariates, edgelist, riskset, actors, start, stop) {
    .Call(`_remstats_dyadStat_choice`, type, covariates, edgelist, riskset, actors, start, stop)
}

tie_choice <- function(covariates, edgelist, actors, riskset, start, stop) {
    .Call(`_remstats_tie_choice`, covariates, edgelist, actors, riskset, start, stop)
}

inertia_choice <- function(edgelist, adjmat, riskset, actors, start, stop, scaling) {
    .Call(`_remstats_inertia_choice`, edgelist, adjmat, riskset, actors, start, stop, scaling)
}

reciprocity_choice <- function(edgelist, adjmat, riskset, actors, start, stop, scaling) {
    .Call(`_remstats_reciprocity_choice`, edgelist, adjmat, riskset, actors, start, stop, scaling)
}

triad_choice <- function(type, edgelist, adjmat, riskset, actors, start, stop, scaling) {
    .Call(`_remstats_triad_choice`, type, edgelist, adjmat, riskset, actors, start, stop, scaling)
}

rrank_choice <- function(type, edgelist, riskset, actors, start, stop) {
    .Call(`_remstats_rrank_choice`, type, edgelist, riskset, actors, start, stop)
}

compute_stats_rate <- function(effects, edgelist, riskset, adjmat, actors, scaling, covariates, interactions, start, stop, verbose) {
    .Call(`_remstats_compute_stats_rate`, effects, edgelist, riskset, adjmat, actors, scaling, covariates, interactions, start, stop, verbose)
}

compute_stats_choice <- function(effects, edgelist, adjmat, actors, riskset, scaling, covariates, interactions, start, stop, verbose) {
    .Call(`_remstats_compute_stats_choice`, effects, edgelist, adjmat, actors, riskset, scaling, covariates, interactions, start, stop, verbose)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_remstats_RcppExport_registerCCallable', PACKAGE = 'remstats')
})
