# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRisksetMatrix <- function(actorID, typeID, N, C, directed) {
    .Call(`_remstats_getRisksetMatrix`, actorID, typeID, N, C, directed)
}

compute_adjmat <- function(edgelist, N, D, directed, memory, memory_value, start, stop) {
    .Call(`_remstats_compute_adjmat`, edgelist, N, D, directed, memory, memory_value, start, stop)
}

compute_stats_tie <- function(effects, edgelist, adjmat, actors, types, riskset, scaling, covariates, interactions, start, stop, directed) {
    .Call(`_remstats_compute_stats_tie`, effects, edgelist, adjmat, actors, types, riskset, scaling, covariates, interactions, start, stop, directed)
}

degree_rc_update <- function(type, edgelist, riskset, actors, memory, memory_value, scaling, start, stop, display_progress) {
    .Call(`_remstats_degree_rc_update`, type, edgelist, riskset, actors, memory, memory_value, scaling, start, stop, display_progress)
}

compute_stats_rate <- function(effects, edgelist, riskset, adjmat, actors, scaling, covariates, interactions, memory, memory_value, start, stop, display_progress) {
    .Call(`_remstats_compute_stats_rate`, effects, edgelist, riskset, adjmat, actors, scaling, covariates, interactions, memory, memory_value, start, stop, display_progress)
}

compute_stats_choice <- function(effects, edgelist, adjmat, actors, riskset, scaling, covariates, interactions, memory, memory_value, start, stop, display_progress) {
    .Call(`_remstats_compute_stats_choice`, effects, edgelist, adjmat, actors, riskset, scaling, covariates, interactions, memory, memory_value, start, stop, display_progress)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_remstats_RcppExport_registerCCallable', PACKAGE = 'remstats')
})
